version: '3.5'

services:

    # Ecoset engine for processing datasets
    ecoset:
        build:
          context: ../../src/engine
          dockerfile: Dockerfile
        ports:
        - "5001"
        - "5002"
        depends_on:
        - redis
        volumes:
        - /sample-data:/data
        - /persistence:/output
        networks:
          - default
          - ecoset_default

    # Cache reqiured for ecoset
    redis:
      image: redis:latest
      command: redis-server --appendonly yes

    # Web application for UI and API
    left:
        build:
          context: ../../
          dockerfile: apps/left-marine/src/Oxlel.LeftMarine.WebUI/Dockerfile
        volumes:
        - "/cache/:/cache/"
        - "/persistence/:/persistence/"
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
        - leftdb
        links:
        - ecoset

    # SQL Server for UI database (accounts, analyses etc.)
    leftdb:
        image: "microsoft/mssql-server-linux:2017-CU12"
        ports:
        - "1433:1433"
        environment:
            SA_PASSWORD: "${MSSQLPASSWORD}"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"

    # nginx for SSL, ddos protection etc. of web app
    reverse-proxy:
        image: nginx:1.17-alpine
        links:
        - left
        depends_on:
        - left
        ports:
          - "5100:5100"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf

# This connection bridges to the GBIF database that is running on another server
networks:
  ecoset_default:
    name: ecoset_default
    driver: bridge