# MarineLEFT/gbif/gbifdb

version: '3'

services:

    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password --local_infile=1
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQLPASSWORD}"
            MYSQL_DATABASE: gbif
            MYSQL_USER: gbif_admin
            MYSQL_PASSWORD: "${MYSQLPASSWORD}"
        ports:
        - "3306:3306"
        volumes:
        - "./vol_files/:/var/lib/mysql/"
        networks:
        - default
        - ecoset_default

    adminer:
        image: adminer:4
        depends_on:
        - db
        ports:
        - "8080:8080"

networks:
  ecoset_default:
    external: true
