version: '3.5'

services:

    # Ecoset engine for processing datasets
    ecoset.api:
      image: docker.pkg.github.com/andrewiom/ecoset-vnext/image:2.1.9
      ports:
      - "5001:5001"
      - "5002:5002"
      environment:
        - ES_CACHE_DIR=/output
      depends_on:
      - ecoset.cache

    # Web application for UI and API
    web.ui:
      build:
        context: ../../
        dockerfile: apps/left/src/Oxlel.Left.WebUI/Dockerfile
      environment:
      - Port=80
      - EcosetEndpoint=http://ecoset.api:5002
      - QT_QPA_PLATFORM=offscreen
      - ConnectionStrings__DefaultConnection=Server=web.db;Database=${MSSQLDBNAME};User=sa;Password=${MSSQLPASSWORD};
      - Tokens__Issuer=${TOKENISSUER}
      - Tokens__Key=${TOKENKEY}
      depends_on:
      - web.db
      - ecoset.api

    # nginx for SSL, ddos protection etc. of web app
    reverse-proxy:
      image: nginx:1.17-alpine
      depends_on:
      - web.ui
      ports:
        - "5100:5100"

    # SQL Server for UI database (accounts, analyses etc.)
    web.db:
      image: "microsoft/mssql-server-linux:2017-CU12"
      ports:
      - "1433:1433"
      environment:
          SA_PASSWORD: "${MSSQLPASSWORD}"
          ACCEPT_EULA: "Y"
          MSSQL_PID: "Express"

    # Cache reqiured for ecoset
    ecoset.cache:
      image: redis:latest
      command: redis-server --appendonly yes
