# MarineLEFT\gbif\python

FROM ubuntu-marineleft

# Set the working directory to /app
WORKDIR /img_files

# Copy the src directory contents into the container at /app
COPY ./img_files /img_files

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Tell Docker about the volumes
VOLUME /vol_files
WORKDIR /vol_files